### ISSUE TITLE
Debug toolbar not showing in Chrome

### ISSUE THREAD

**Issue by soderluk** [malyshev/yii-debug-toolbar#122]
The HTML of the toolbar is visible when viewing source, but Chrome does not show the toolbar at all.
Toolbar works normally on Firefox. Chrome somehow messes up the HTML when the toolbar HTML is outside the <html></html> tags.

**Comment by grigory51** [comment]
Removing position: fixed of #ydtb-toolbar on main.css:37 fix panel in chrome. it is bag.

**Comment by PrplHaz4** [comment]
I've had the same problem as well - seems to have appeared when we updated the app to use Bootstrap 3.2.0 (YiiBooster 4.01) - and does not seem to be chrome-specific.

The fix provided by @grigory51 seems to work great.  Thanks!

Added this to mysite.css:

```
/* fix for yii-debug-toolbar not showing */
#ydtb-toolbar {
    position: inherit;
}
```

**Comment by fedemotta** [comment]
Same issue here. @PrplHaz4 fix works with a minor tweak.

``` css
/* fix for yii-debug-toolbar not showing */
#ydtb-toolbar {
    position: inherit!important;
}
```
